In [1]:
from PandasModularParts.pd_M1_SurrogateWeights import SurrogateWeights
import pandas as pd
from ModularParts.M5_PrometheePreferenceWithInteractions import PrometheePreferenceWithInteractions
from PandasModularParts.pd_M3_PrometheePreference import PrometheePreference
from Tests.DecisionProblemData import *

criteria = ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g7']
ranking = SurrogateWeights(ranked_criteria=pd.Series(data=[7, 1, 3, 2, 4, 5, 6], index=criteria)).rank_sum()
print(pd.Series(data=[7, 1, 3, 2, 4, 5, 6], index=criteria))
print(ranking)
preference, partial_preference = PrometheePreference(alternatives_performances=
                                                     pd.DataFrame(data=alternatives_performances, index=alternatives,
                                                                  columns=criteria), weights=ranking,
                                                     criteria_features=df_criteria
                                                     ).computePreferenceIndices()

print("----------------------PREFERENCE--------------")
print(type(partial_preference))
partial_preference


g1    7
g2    1
g3    3
g4    2
g5    4
g6    5
g7    6
dtype: int64
g1    0.036
g2    0.250
g3    0.179
g4    0.214
g5    0.143
g6    0.107
g7    0.071
dtype: float64
----------------------PREFERENCE--------------
<class 'pandas.core.frame.DataFrame'>


a1   a2   a3   a4   a5   a6   a7   a8   a9  a10  ...  \
criteria alternatives                                                    ...   
g1       a1            0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   
         a2            0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...   
         a3            0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   
         a4            0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...   
         a5            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   
...                    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
g7       a36           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
         a37           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
         a38           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
         a39           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
         a40           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   

                       a31  a32  a33  a34  a35  a36  a37  a38  a39  a40  
criteria alternatives                                                    
g1       a1            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
         a2            0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  
         a3            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
         a4            0.0  1.0  0.0  0.7  1.0  1.0  1.0  1.0  1.0  1.0  
         a5            0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  
...                    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
g7       a36           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
         a37           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
         a38           0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0  
         a39           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
         a40           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[280 rows x 40 columns]

In [26]:
df_criteria = pd.DataFrame(zip(criteria_weights, preference_thresholds, indifference_thresholds,
                               reinforced_preferences, reinforcement_factors, standard_deviations,
                               criteria_directions, criteria_ranks, generalized_criteria),

                           index=criteria,
                           columns=['criteria_weights', 'preference_thresholds', 'indifference_thresholds',
                                    'reinforced_preferences', 'reinforcement_factors', 'standard_deviations',
                                    'criteria_directions', 'criteria_ranks', 'generalized_criteria'])
df_criteria

criteria_weights  preference_thresholds  indifference_thresholds  \
g1             0.073                      2                        1   
g2             0.370                      4                        4   
g3             0.228                      3                        1   
g4             0.109                      3                        0   
g5             0.156                      3                        1   
g6             0.020                      0                        0   
g7             0.044                      0                        0   

    reinforced_preferences  reinforcement_factors standard_deviations  \
g1                       4                    1.2                None   
g2                       8                    1.2                None   
g3                       6                    1.2                None   
g4                       6                    1.3                None   
g5                       6                    1.1                None   
g6                       3                    1.1                None   
g7                       3                    1.1                None   

    criteria_directions  criteria_ranks  \
g1                    1               5   
g2                    1               1   
g3                    0               2   
g4                    0               4   
g5                    0               3   
g6                    1               7   
g7                    1               6   

                       generalized_criteria  
g1  PreferenceFunction.V_SHAPE_INDIFFERENCE  
g2               PreferenceFunction.U_SHAPE  
g3                 PreferenceFunction.LEVEL  
g4               PreferenceFunction.V_SHAPE  
g5  PreferenceFunction.V_SHAPE_INDIFFERENCE  
g6                 PreferenceFunction.USUAL  
g7                 PreferenceFunction.USUAL

In [12]:

import pandas as pd
multi_index = pd.MultiIndex.from_tuples([("r0", "rA"),
                                       ("r1", "rB")],
                                       names=['Courses','Fee'])
multi_index

ValueError: Length of names must match number of levels in MultiIndex.

In [13]:

cols = pd.MultiIndex.from_tuples([("Gasoline", "Toyoto"),
                                  ("Toyoto", "Ford"),
                                  ("Electric", "Tesla"),
                                  ("Electric", "Nio")])
data=[[100,300, 900,400 ], [200,500, 300,600]]

df = pd.DataFrame(data, columns= [Toyoto , "Ford", ],index=multi_index)
df

NameError: name 'Toyoto' is not defined

In [15]:
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns=["first", "second"],
)


pd.MultiIndex.from_frame(df)
df

first second
0   bar    one
1   bar    two
2   foo    one
3   foo    two

In [17]:

import pandas as pd
# Create Row Level MultiIndex
new_index = pd.MultiIndex.from_tuples([("r0", "rA"),
                                       ("r0", "rB")],
                                       names=['indx1','indx2'])

# Create Column Level MultiIndex
cols = pd.MultiIndex.from_tuples([("Gasoline", "Toyoto"),
                                  ("Gasoline", "Ford"),
                                  ("Electric", "Tesla"),
                                  ("Electric", "Nio")])

# Create MultiIndex DataFrame
data=[[100,300, 900,400 ], [200,500, 300,600]]
df = pd.DataFrame(data, columns=cols,index=new_index)
print(df)

# Convert MultiIndex to Columns
df2=df.reset_index()
print(df2)

# Convert MuliIndex to Single index
df2 = df.reset_index(level=[1])
print(df2)

# Drop Index
df2 = df.reset_index(level=[1], drop=True)
print(df2)

# Flattern MultiIndex columns
df.columns = df.columns.get_level_values(1)
print(df)

#Drop Index from MultiIndex
df=df.droplevel(0, axis=0)
print(df)


            Gasoline      Electric     
              Toyoto Ford    Tesla  Nio
indx1 indx2                            
r0    rA         100  300      900  400
      rB         200  500      300  600
  indx1 indx2 Gasoline      Electric     
                Toyoto Ford    Tesla  Nio
0    r0    rA      100  300      900  400
1    r0    rB      200  500      300  600
      indx2 Gasoline      Electric     
              Toyoto Ford    Tesla  Nio
indx1                                  
r0       rA      100  300      900  400
r0       rB      200  500      300  600
      Gasoline      Electric     
        Toyoto Ford    Tesla  Nio
indx1                            
r0         100  300      900  400
r0         200  500      300  600
             Toyoto  Ford  Tesla  Nio
indx1 indx2                          
r0    rA        100   300    900  400
      rB        200   500    300  600
       Toyoto  Ford  Tesla  Nio
indx2                          
rA        100   300    900  400
rB        200 

In [22]:
import numpy as np

np.random.seed(10)
arr = np.random.randint(10, size=(5,3,2))
print (arr)
print(arr.shape)

arr = arr.transpose(1,2,0)
df = pd.concat([pd.DataFrame(x) for x in arr], keys=np.arange(arr.shape[2]))
df

[[[9 4]
  [0 1]
  [9 0]]

 [[1 8]
  [9 0]
  [8 6]]

 [[4 3]
  [0 4]
  [6 8]]

 [[1 8]
  [4 1]
  [3 6]]

 [[5 3]
  [9 6]
  [9 1]]]
(5, 3, 2)


0  1  2  3  4
0 0  9  1  4  1  5
  1  4  8  3  8  3
1 0  0  9  0  4  9
  1  1  0  4  1  6
2 0  9  8  6  3  9
  1  0  6  8  6  1